//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleAuthen
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public string UserName { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public string UserPassword { get; set; }
        public string UserRole { get; set; }
        public string UserEmailId { get; set; }
    }
}
